- hosts: bastions
  become: true
  gather_facts: False
  tasks:
    - name: Install words
      yum:
        name: words

    - name: 01_test
      shell: "{{ item }}"
      register: output_01
      args:
        chdir: /root/
      loop:
        - sort -R  /usr/share/dict/words | head -1
        - sort -R  /usr/share/dict/words | head -2
        - sort -R  /usr/share/dict/words | head -3
        - sort -R  /usr/share/dict/words | head -4
        - sort -R  /usr/share/dict/words | head -5
    - debug: var=output_01

    - name: 02_test
      shell: "{{ item }}"
      register: output_02
      args:
        chdir: /root/
      loop:
        - sort -R  /usr/share/dict/words | head -6
        - sort -R  /usr/share/dict/words | head -7
        - sort -R  /usr/share/dict/words | head -8
        - sort -R  /usr/share/dict/words | head -9
        - sort -R  /usr/share/dict/words | head -10
    - debug: var=output_02

    - name: Output Lab01
      agnosticd_user_info:
        msg: 
          - "command: {{ item.cmd }}"
          - "result: {{ item.stdout }}"
      loop: "{{ output_01.results }}"

    - name: Output Lab02
      agnosticd_user_info:
        msg: 
          - "command: {{ item.cmd }}"
          - "result: {{ item.stdout }}"
      loop: "{{ output_02.results }}"     
