---
- loop: "{{ infra_images_instances | default([]) }}"
  when: _instance.image is defined and _instance.image is mapping
  loop_control:
    loop_var: _instance
  include_tasks: ec2_loop_image.yaml

- when: agnosticd_images is defined
  block:
    - name: debug agnosticd_image
      debug:
        var: agnosticd_images
        verbosity: 3

    - name: Print images found for each instance
      loop_control:
        label: "{{ item.key }}"
      debug:
        msg: "{{ item.key }} - {{ item.value.name }} - {{ item.value.image_id }}"
      loop: "{{ agnosticd_images | dict2items }}"
