---
- name: Create migration host group
  add_host:
    name: "{{ import_host }}"
    ansible_become: true
    ansible_ssh_private_key_file: "{{ migration_key_path | default(omit) }}"
    ansible_user: "opentlc-mgr"
    bastion: "{{ import_host }}"
    group: "migration"
    output_dir: "{{ output_dir }}"
    remote_user: "opentlc-mgr"

- name: Download images from project
  become: true
  delegate_to: "{{ import_host }}"
  environment: "{{ __infra_osp_download_images_authentication | combine(__infra_osp_download_images_import_host_environment) }}"
  convert_blueprint:
    ibm_endpoint: "{{ ibm_endpoint }}"
    ibm_auth_endpoint: "{{ ibm_auth_endpoint }}"
    ibm_api_key: "{{ ibm_api_key }}"
    ibm_resource_id: "{{ ibm_resource_id }}"
    bucket: "{{ ibm_bucket_name }}"
    project: "{{ image_store }}"
    output_dir: "{{ output_dir }}"
    mode: "download"
    glance_pool: "{{ ceph_cluster | default('red') }}-images"
    overwrite: "{{ overwrite_image | default('false') }}"
