---
- name: Step 005 Environment specific Software
  hosts: localhost
  gather_facts: False
  become: false
  tasks:
    - debug:
        msg: "Software tasks Started"


- name: Configure httpd
  hosts: bastions
  become: true
  tasks:
    - name: Install httpd
      yum:
        name: httpd

    - name: Copy horizon.conf
      template:
        src: httpd/horizon.conf
        dest: /etc/httpd/conf.d/horizon.conf
        
    - name: Start and enable httpd
      service:
        name: httpd
        state: restarted
        enabled: yes

    - name: Allow SELinux rule to allow httpd to connect network 
      shell: setsebool -P httpd_can_network_connect 1

- name: Software flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:
    - debug:
        msg: "Software checks completed successfully"
