---
- name: Install Post Software dynamic roles
  hosts: all
  gather_facts: false
  tags:
    - dynamic_roles
  tasks:
    - name: Process facts
      loop: "{{ agnosticd_post_software_roles | default([]) }}"
      loop_control:
        loop_var: _role
        label: "{{ _role.name }}"
      when: >-
        _role.facts | default({}) | length > 0
        and
        {{ _role.when | default(true) }}
        and
        (
          _role.host | default('') == inventory_hostname
          or
          _role.group | default('') in group_names
          or
          _role.groups | default([])
          | intersect(group_names) | list | length > 0
        )

      vars:
        _facts: "{{ _role.facts }}"
      include_tasks: facts_tasks.yaml

    - name: Process roles
      vars:
        agnosticd_stage: post_software
      loop: "{{ agnosticd_post_software_roles | default([]) }}"
      loop_control:
        loop_var: _role
        label: "{{ _role.name }}"
      include_role:
        apply:
          tags:
            - post_software
        name: "{{ _role.name }}"
        defaults_from: "{{ _role.defaults_from | default('main') }}"
        handlers_from: "{{ _role.handlers_from | default('main') }}"
        tasks_from: "{{ _role.tasks_from | default('main') }}"
        vars_from: "{{ _role.vars_from | default('main') }}"
      when: >-
        _role.name | default('') != ''
        and
        {{ _role.when | default(true) }}
        and
        (
          _role.host | default('') == inventory_hostname
          or
          _role.group | default('') in group_names
          or
          _role.groups | default([]) | intersect(group_names) | list | length > 0
        )
