---
version: 1

build_arg_defaults:
  #EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:stable-2.9-latest'
  #EE_BASE_IMAGE: registry.redhat.io/ansible-automation-platform-21/ee-supported-rhel8:1.0.1-2
  #EE_BASE_IMAGE: registry.redhat.io/ansible-automation-platform-21/ee-29-rhel8:1.0.0-33
  EE_BASE_IMAGE: registry.redhat.io/ansible-automation-platform-21/ee-minimal-rhel8:latest

ansible_config: 'ansible.cfg'

dependencies:
  #galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend: |
    RUN whoami
    RUN cat /etc/os-release
    COPY oc_client.sh oc_client.sh
  append:
    - RUN pip3 freeze
    - RUN ./oc_client.sh
