---
cloud_provider: equinix_metal
remote_user: root
cloud_tags:
  ci_org_owner: Customer And Field engagement BU
  env_type: '{{ env_type }}'
  platform: '{{ platform | d(''unknown'') }}'
env_type: just-a-bunch-of-nodes
extra_sno_nodes: false
hypervisor_count: 1
hypervisor_os: centos_8
install_bastion: false
install_common: false
install_ftl: false
install_student_user: true
key_name: opentlc_admin_backdoor
ocp4_aio_deploy_acm: false
ocp4_aio_deploy_acs: false
ocp4_aio_deploy_cnv: false
ocp4_aio_deploy_cnvlab: true
ocp4_aio_deploy_compact: false
ocp4_aio_deploy_disconnected: false
ocp4_aio_deploy_guacamole: true
ocp4_aio_deploy_ipi: true
ocp4_aio_deploy_nfs: false
ocp4_aio_deploy_ocp: true
ocp4_aio_deploy_ocp_plus: false
ocp4_aio_deploy_ocs: true
ocp4_aio_deploy_ods: false
ocp4_aio_deploy_sno: false
ocp4_aio_deploy_type: ipi
deploy_type: ipi
ocp4_aio_ocp_version: 4.9.5
ocp4_aio_ocp_workers: 3
ocp4_aio_baremetal_provider: "{{ cloud_provider }}"
ocp4_aio_rhcos_iso_url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/latest/latest/rhcos-live.x86_64.iso
ocp4_aio_use_ddns: true
own_repo_path: http://d3s3zqyaz8cp2d.cloudfront.net/repos/ocp/{{osrelease}}
platform: dev
pull_secret: '{{ ocp4_pull_secret }}'
purpose: production
repo_method: none
set_env_authorized_key: false
override_deploy_ocp: >-
  {{ ( ocp4_aio_deploy_ocs
  or ocp4_aio_deploy_cnv
  or ocp4_aio_deploy_acm ) | bool
  }}
override_deploy_compact: "{{ ocp4_aio_ocp_workers != 0 }}"
override_deploy_nfs: "{{ not ocp4_aio_deploy_ocs | bool }}"

equinix_metal_facility: am6
hypervisor_type: s3.xlarge.x86

ansible_user: root

# Environment Instances
instances:
  - name: "hypervisor"
    count: "{{ hypervisor_count }}"
    public_dns: true
    type: "{{ hypervisor_type }}"
    os: "{{ hypervisor_os }}"
    facility: "{{ equinix_metal_facility }}"
    tags:
      - key: "AnsibleGroup"
        value: "bastions,hypervisors"
      - key: "ostype"
        value: "linux"

requirements_content:
  roles:
    - src: https://github.com/fridim/ocp4_aio_infra_role_base_software.git
      scm: git
      name: ocp4_aio_base_software
      version: main

    - name: ocp4_aio_base_virt
      src: https://github.com/RHFieldProductManagement/ocp4_aio_infra_role_base_virt.git
      scm: git
      version: v0.0.3

    - name: ocp4_aio_prepare_bastion
      src: https://github.com/RHFieldProductManagement/ocp4_aio_infra_role_prepare_bastion.git
      scm: git
      version: v0.0.2

    - name: ocp4_aio_role_acm
      src: https://github.com/RHFieldProductManagement/ocp4_aio_role_acm.git
      scm: git
      version: v0.0.1

    - name: ocp4_aio_role_acs
      src: https://github.com/RHFieldProductManagement/ocp4_aio_role_acs.git
      scm: git
      version: v0.0.1

    - name: ocp4_aio_role_cnv
      src: https://github.com/RHFieldProductManagement/ocp4_aio_role_cnv.git
      scm: git
      version: v0.0.1

    - name: ocp4_aio_role_imgreg
      src: https://github.com/RHFieldProductManagement/ocp4_aio_role_imgreg.git
      scm: git
      version: v0.0.1

    - name: ocp4_aio_role_nfsmount
      src: https://github.com/RHFieldProductManagement/ocp4_aio_role_nfsmount.git
      scm: git
      version: v0.0.2

    - name: ocp4_aio_role_ocs
      src: https://github.com/RHFieldProductManagement/ocp4_aio_role_ocs.git
      scm: git
      version: v0.0.3

    - name: ocp4_aio_deploy_bastion
      src: https://github.com/RHFieldProductManagement/ocp4_aio_infra_role_deploy_bastion.git
      scm: git
      version: v0.0.3

    - name: ocp4_aio_deploy_guac
      src: https://github.com/RHFieldProductManagement/ocp4_aio_infra_role_deploy_guacamole.git
      scm: git
      version: v0.0.1

    - name: ocp4_aio_deploy_ocp
      src: https://github.com/RHFieldProductManagement/ocp4_aio_infra_role_deploy_ocp.git
      scm: git
      version: v0.0.4

    - name: ocp4_aio_workload_cnvlab
      src: https://github.com/RHFieldProductManagement/ocp4_aio_role_deploy_cnvlab.git
      scm: git
      version: v0.0.2

    # PoC, implement rogue tasks as roles

    - name: ocp4_equinix_aio_post_infra
      src: https://github.com/fridim/ocp4_equinix_aio_post_infra
      version: main

    - name: ocp4_equinix_aio_set_guid
      src: https://github.com/fridim/ocp4_equinix_aio_set_guid
      version: main

    - name: ocp4_equinix_metal_kube
      src: https://github.com/fridim/ocp4_equinix_metal_kube
      version: main

  collections:
    - name: community.general
    - name: containers.podman


agnosticd_post_infra_roles:
  - name: ocp4_equinix_aio_post_infra

agnosticd_pre_software_roles:
  - name: ocp4_equinix_aio_set_guid
    group: hypervisors

  - name: bastion-student-user
    group: hypervisors
    when: install_student_user

  - name: ocp4_aio_base_software
    group: hypervisors

  - name: ocp4_aio_base_virt
    group: hypervisors
    facts:
      aio_host_ip_address: "{{ hostvars['hypervisor']['public_ip_address'] }}"

  - name: ocp4_aio_prepare_bastion
    group: hypervisors
    facts:
      ocp4_aio_ssh_key: "{{ lookup('file', '{{ output_dir }}/{{ guid }}_id_rsa.pub' ) }}"

  - name: ocp4_aio_deploy_guac
    group: hypervisors
    when: ocp4_aio_deploy_guacamole

  - name: ocp4_aio_deploy_bastion
    host: bastion-vm
    facts:
      ocp4_aio_ssh_key: "{{ lookup('file', '{{ output_dir }}/{{ guid }}_id_rsa.pub' ) }}"

agnosticd_software_roles:
  - name: ocp4_aio_deploy_ocp
    host: bastion-vm
    facts:
      aio_host_ip_address: "{{ hostvars['hypervisor']['public_ip_address'] }}"

agnosticd_post_software_roles:
  # Setup OCS Storage
  - name: ocp4_aio_role_ocs
    host: bastion-vm

  # Enable internal registry
  - name: ocp4_aio_role_imgreg
    host: bastion-vm
