---

# sample vars configuration file
env_type: ansible-advanced-v2    # Name of config to deploy
output_dir: /tmp/output_dir             # Writable working scratch directory
email: name@example.com                 # User info for notifications
guid: guid01                            # Your Global UNIQUE Identifier
cloud_provider: osp                     # Which AgnosticD Cloud Provider to use

# Image project to download image
ibm_image_store:
  - ansible-dev-images

# Control user settings for Role: control-user
control_user_name: devops
control_user_resource_dir_name: materials
control_user_ssh_config: ./files/ssh_config.j2
control_user_directories:
  - ".config/openstack"
control_user_copy_user_templates:
  - template: ./files/clouds.yaml.j2
    resource: clouds.yaml
    home: .config/openstack/clouds.yaml

# Lab Manager's variable
lab_mgr_dir: /srv/lab-manager
lab_mgr_release: release-1.0.1

#Satellite
repo_method: satellite

# Satellite CA Cert
set_repositories_satellite_ca_cert: |
  -----BEGIN CERTIFICATE-----
  MIIG5jCCBM6gAwIBAgIJALINJ23FT6eCMA0GCSqGSIb3DQEBCwUAMIGAMQswCQYD
  VQQGEwJVUzEXMBUGA1UECAwOTm9ydGggQ2Fyb2xpbmExEDAOBgNVBAcMB1JhbGVp
  Z2gxEDAOBgNVBAoMB0thdGVsbG8xFDASBgNVBAsMC1NvbWVPcmdVbml0MR4wHAYD
  VQQDDBVzYXRlbGxpdGUuZXhhbXBsZS5jb20wHhcNMjEwMzIyMDM0OTIxWhcNMzgw
  MTE4MDM0OTIxWjCBgDELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9s
  aW5hMRAwDgYDVQQHDAdSYWxlaWdoMRAwDgYDVQQKDAdLYXRlbGxvMRQwEgYDVQQL
  DAtTb21lT3JnVW5pdDEeMBwGA1UEAwwVc2F0ZWxsaXRlLmV4YW1wbGUuY29tMIIC
  IjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA29bCSv+CU3B3hqPwksZd2KzQ
  TipmVPMIhMSME+v6u+LchLHHB9OmW/k+6cgLihB6e+R5LS5bIybRWW81CNLE7Pli
  m8zPYHvl1wchnE9uHxEyO3K7IM6EMztrcEK//DzaHrBIiOhi2hzGwuWqtptKwHZR
  XtL80jTdturBquURAqKy+dDJ3qdHw56MoyVWmR6dSnTaTCbCS760AfXsAPipNS06
  r9sANre6KKS4YIV9WeumsPLHGljFSwSkdzr8kOhF7y9QgcyYXJvEgARiQeSeaXTz
  nuN2Omr4xsbJ41HXj3JGo9rMDWWLQQXr/d/2JRZUsxoROItW1e5h13OluwUn+FzX
  i3EB1AZVqkb8KpC7Wt8EavRaEkexIZQB6aklOxATlvRPp8MjA/Jkyc9vlnQODNQh
  ZjMKHQnrwXwNK2t+O1xQsLdTVqucTgWYUno6pePhWMshSbooNQrjgMa4w1xUfNsH
  17STUj6P2pNdvGwcdJhT64SoM/dZGRq2z/YWCsmSOmIGA8FH32xXTCHbqzbexHIT
  x2BnwU72goUADax5euMRGifqw5fD5Yi+dCHE1YYMf8rAf85uTVaYzZSMPsk17YFZ
  Y25DnoAbmWA9sUzVp4H3vFa6hO3sJgPrnAX+KpsXSqq8TEZTNITj5abzeyWhv98y
  EBl2ImXcLPVJ+9jNEpcCAwEAAaOCAV8wggFbMAwGA1UdEwQFMAMBAf8wCwYDVR0P
  BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjARBglghkgBhvhC
  AQEEBAMCAkQwNQYJYIZIAYb4QgENBCgWJkthdGVsbG8gU1NMIFRvb2wgR2VuZXJh
  dGVkIENlcnRpZmljYXRlMB0GA1UdDgQWBBT2KaXMZ8cJSoquybEfYm/8mmGUlzCB
  tQYDVR0jBIGtMIGqgBT2KaXMZ8cJSoquybEfYm/8mmGUl6GBhqSBgzCBgDELMAkG
  A1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQHDAdSYWxl
  aWdoMRAwDgYDVQQKDAdLYXRlbGxvMRQwEgYDVQQLDAtTb21lT3JnVW5pdDEeMBwG
  A1UEAwwVc2F0ZWxsaXRlLmV4YW1wbGUuY29tggkAsg0nbcVPp4IwDQYJKoZIhvcN
  AQELBQADggIBALFgQJQK4wYq1n/3y9TtT9nVbe0tvquC2XVErBSv4AmBcEF8/QTV
  C/ma6a1oTi/5gZi7Fr3OcedlZ1du9VxBMKxqXT95lyZpLoYXjwQv38MLmefiCTnw
  aO177k+C+FdCoH8/c/ugPTZqpnfr3QfMAuin5YOlrM7vq7IHhlUtOSSiafS7wg1v
  I0nPu0RBn5KvfeqI1NiEs7ClPHgrSPTx4IRSODHwka98W4NhohUFjMCCgDxxQvTM
  fvNSA9tf+D8QehhcxvuYb9sNw1HVRGsJ/w9IqXpGp7CbjlhuE+1zXVjByXugkvdc
  KBMEXWDlwotfOoYhzKgHdxYGj41yTfoAl4/+SMl8E07PWlKiDE2Hvk/Gtk8+oA8e
  GO8S/6EeVDpv+1rBG/dY4bu1JQitiWgGXxF0sAqB4ESQWZbiWX4y8IYKkUPvsyvo
  afoG+iAyLXjYelZGOBNGSPZB17+UG1HaoeSh1s+iKqIjfW0LKHQJCIzklqP+4FjL
  gVjaM757pwWcnDIS+igl/PeFzSKQwe2UFkanrXQv+jIQJSCs59tf0mKewjkvSpQr
  sYFXlrHtuyn/+MEnSiSS5QdlkSTZoCgU1qkh2ARFoFjWV7h7xTwKeaoY07PmsgZZ
  FVp9fFT81xyhvYlit45D/IxKDC4Mm4EcEwBbVaHvGSOD7M/fj7RkTQLq
  -----END CERTIFICATE-----
# VScoder server variables
vscode_user_name: "{{ control_user_name }}"
vscode_server_hostname: "{{ groups['bastions'][0] | regex_replace('\\..*$') }}.{{ guid }}.{{ osp_cluster_dns_zone }}"


podman_yum_packages:
  - podman-2.2.1-7*
  - python3



# Update RHEL to the latest packages (and reboot)
update_packages: true


ocp_workload: ocp4_workload_shared_cluster_access

# --- Workload parameters
ocp4_workload_shared_cluster_access_user_groups:
  - OPENTLC-PROJECT-PROVISIONERS
ocp4_workload_shared_cluster_access_create_quota: true
ocp4_workload_shared_cluster_access_quota_name: "clusterquota-shared-{{ guid }}"
ocp4_workload_shared_cluster_access_quota:
  hard:
    requests.cpu: "16"
    limits.cpu: "16"
    requests.memory: 20Gi
    limits.memory: 45Gi
    pods: "30"
    configmaps: "100"
    secrets: "150"
    services: "150"
    persistentvolumeclaims: "15"
    requests.storage: 50Gi

# --- Ensure the workload prints the correct statements for CloudForms to realize it finished
workload_shared_deployment: true



target_host_ansible_host: bastion.dev4.openshift.opentlc.com


target_host:
  ansible_host: "{{ target_host_ansible_host }}"
  ansible_port: 22
  ansible_user: ec2-user
  ansible_ssh_private_key_file: ~/.ssh/opentlc_admin_backdoor.pem

...
