---
- name: Step 002 Post Infrastructure
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - debug:
        msg: "Step 002 Post Infrastructure"

- name: Configure all hosts authorized_keys
  hosts:
    - all:!windows
  become: true
  gather_facts: false
  tags:
    - common_tasks
  tasks:

    - include_role:
        name: set_env_authorized_key
      when: set_env_authorized_key | bool
