---
- name: Step 000 Pre Infrastructure
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - debug:
        msg: "Step 000 Pre Infrastructure"

    - include_role:
        name: infra-local-create-ssh_key
      when: set_env_authorized_key | bool
