---
# - name: Verify everything is deployed correctly
#   include_tasks: verify-workload.yaml

# Implement your Post Workload deployment tasks here
- name: output workshop info
  agnosticd_user_info:
    msg: "{{ item }}"
  loop:
    - ""
    - "DG Workshop provisioned for {{ num_users }} user(s)"
    - ""
    - "URL for attendees to get a username assigned to them and links to labs:"
    - ""
    - "https://get-a-username-guides.{{ route_subdomain }}"
    - ""
    - "You should share this URL (or a shortlink for it) -- It is all they will need to get started!"
    - ""
    - "[Instructor Only] To access the admin see which user is assigned to which user ID, use the following:"
    - ""
    - "[Instructor Only] https://get-a-username-guides.{{ route_subdomain }}/admin"
    - ""
    - "[Instructor Only] Admin login with 'admin' / '{{ workshop_openshift_user_password }}'"
    - ""
    - >-
      Workshop User Guide (in case you need them for direct linking):
      http://web-guides.{{ route_subdomain }}
    - ""
    - >-
      OpenShift credentials for attendees:
      {{ workshop_openshift_user_name }} / {{ workshop_openshift_user_password }}
    - >-
      CodeReady Workspaces credentials for attendees:
      {{ workshop_che_user_name }} / {{ workshop_che_user_password }}
    - ""
    - "OpenShift Console: {{ console_url }}"
    - "Cluster admin login with '{{ ocp_username }}' / {{ workshop_openshift_admin_password }}"
    - ""
    - "OpenShift/Kubernetes API (use with oc login): {{ master_url }}"
    - ""
    - "CodeReady Console: https://codeready-codeready.{{ route_subdomain }}"
    - "Admin login with 'admin' / 'admin'"
    - ""
    - "Red Hat SSO Console: https://keycloak-codeready.{{ route_subdomain }}"
    - "Find admin credentials with oc set env deployment/keycloak -n codeready --list"
    - ""
    - "NOTE: Workspaces in CodeReady are provisioned asynchronously and may not"
    - "be accessible until rollout finishes shortly."
  when: not silent|bool

# Leave this as the last task in the playbook.
- name: post_workload tasks complete
  debug:
    msg: "Post-Workload Tasks completed successfully."
  when: not silent | bool
